### ISSUE TITLE
Stations shown after they have already been stopped at

### ISSUE THREAD

**Issue by mathstrains21** [benfl3713/DepartureBoard#255]
**Describe the bug**
On the Far North Line, Trains go Inverness, lots of stations, Georgemas Junction, Thurso, Georgemas Junction, Wick and vice versa. This means trains stop at Georgemas Junction twice. On the departure boards, it is correctly showing the time for each train, but it is adding extra stops in for the second train, which it has already stopped at.

**To Reproduce**
1. Go to https://www.leddepartureboard.com/GGJ
2. Look at the stops for each pair, both say "Thurso, Georgemas Junction"

**Expected behavior**
The second time shouldn't say those two stations on the list.

This can probably be fixed by checking the time of the stop, rather than just looking for the stop and then printing all subsequent stops.

**Comment by ben-fletcher** [comment]
I @mathstrains21 that is a very interesting scenario you have found. 

Just to confirm I am understanding it correctly can you confirm what I have said below:

So the screenshot below has 2 departures, which is correct as it stops twice at the same place.
However the second one shouldn't have the 2 stops I have highlighted in red.

![image](https://user-images.githubusercontent.com/48907264/164434081-80dce3f5-ab96-4e57-a59a-975b786ec656.png)

I think you're right that to fix it I need to also look at the time rather than just the name. The assumption at the time is that a train won't stop at the same station twice however you seem to of found an example that does. I shall take a look at fixing it this way.

Thanks for identifying and raising the bug 👍

**Comment by mathstrains21** [comment]
I can confirm that your understanding of the problem is correct!

**Comment by ben-fletcher** [comment]
Issue has been fixed and will be deployed in the next 5ish minutes
