### ISSUE TITLE
Platform 1 shown for all departures at some stations

### ISSUE THREAD

**Issue by CrispyUK** [benfl3713/DepartureBoard#75]
Some stations are displaying Platform 1 for all departures. A few examples if this helps identify any pattern:

https://leddepartureboard.com/HNK
https://leddepartureboard.com/CAA
https://leddepartureboard.com/BKW
https://leddepartureboard.com/LGE

These are all 2 platform stations, although the issue doesn't happen with every 2 platform station.

**Comment by benfl3713** [comment]
The reason they were showing one was because of the real time api not being able to provide a platform, so I defaulted to 1. To be more accurate I have now changed it to not show a platform if none is provided.
![image](https://user-images.githubusercontent.com/44288013/81001775-23ece400-8e40-11ea-9588-4b5c65377ef9.png)
